name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.24"

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic ./...
          go test -json ./... > test.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.txt
          verbose: true

      - name: Run benchmarks (Standard Queue)
        run: go test -bench=. -benchmem ./internal/concurrent_queue/

      - name: Run benchmarks (Void Queue)
        run: go test -bench=. -benchmem ./internal/concurrent_queue/void_queue/
